In [31]:
## Read the dataset
import pandas as pd
import sqlite3

df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [32]:
## Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [33]:
## Display statistical summary of the dataset
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [34]:
## Check for missing values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [35]:
## We will replace missing values in 'Review Rating' with the median rating of that product category
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [36]:
## Rename columns for better readability and consistency
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [37]:
## Create a column age_group based on age
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle Aged
1   19  Young Adult
2   50  Middle Aged
3   21  Young Adult
4   45  Middle Aged
5   46  Middle Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle Aged

In [38]:
## Create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [39]:
## Display first 10 rows of discount_applied and promo_code_used columns
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [40]:
## Compare two columns discount_applied and promo_code_used
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [41]:
## Drop promo_code_used column as both columns are identical
df = df.drop(columns=['promo_code_used'])
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [42]:
# Create SQLite database in memory

conn = sqlite3.connect(':memory:')

In [43]:
# Convert CSV to SQL table

df.to_sql('shopping_behavior', conn, index=False, if_exists='replace')

3900

In [44]:
# Q1 Total revenue by gender

query = """
SELECT
    "Gender",
    SUM("Purchase Amount (USD)") AS revenue
FROM shopping_behavior
GROUP BY "Gender";
"""

pd.read_sql_query(query, conn)

   gender  revenue
0  Female      0.0
1    Male      0.0

In [45]:
# Q2 Customers who used discount and spent above average

query = """
SELECT
    "Customer ID",
    "Purchase Amount (USD)"
FROM shopping_behavior
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >= (
    SELECT AVG("Purchase Amount (USD)")
    FROM shopping_behavior
);
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: ["Customer ID", "Purchase Amount (USD)"]
Index: []

In [46]:
# Q3 Top 5 products with highest review rating

query = """
SELECT
    "Item Purchased",
    ROUND(AVG("Review Rating"),2) AS avg_rating
FROM shopping_behavior
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

  "Item Purchased"  avg_rating
0   Item Purchased         0.0

In [47]:
# Q4 Average purchase amount by shipping type

query = """
SELECT
    "Shipping Type",
    ROUND(AVG("Purchase Amount (USD)"),2) AS avg_purchase
FROM shopping_behavior
WHERE "Shipping Type" IN ('Standard','Express')
GROUP BY "Shipping Type";
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: ["Shipping Type", avg_purchase]
Index: []

In [48]:
# Q5 Subscribers vs Non-Subscribers spending


query = """
SELECT
    "Subscription Status",
    COUNT("Customer ID") AS total_customers,
    ROUND(AVG("Purchase Amount (USD)"),2) AS avg_spend,
    ROUND(SUM("Purchase Amount (USD)"),2) AS total_revenue
FROM shopping_behavior
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC;
"""

pd.read_sql_query(query, conn)

  "Subscription Status"  total_customers  avg_spend  total_revenue
0   Subscription Status             3900        0.0            0.0

In [49]:
# Q6 Products with highest discount rate


query = """
SELECT
    "Item Purchased",
    ROUND(
        100.0 * SUM(CASE WHEN "Discount Applied"='Yes' THEN 1 ELSE 0 END)/COUNT(*),
        2
    ) AS discount_rate
FROM shopping_behavior
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

  "Item Purchased"  discount_rate
0   Item Purchased            0.0

In [50]:
# Q7 Customer segmentation

query = """
WITH customer_type AS (
    SELECT
        "Customer ID",
        "Previous Purchases",
        CASE
            WHEN "Previous Purchases" = 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM shopping_behavior
)
SELECT
    customer_segment,
    COUNT(*) AS num_customers
FROM customer_type
GROUP BY customer_segment;
"""

pd.read_sql_query(query, conn)

  customer_segment  num_customers
0            Loyal           3900

In [51]:
# Q8 Top 3 products in each category


query = """
WITH item_counts AS (
    SELECT
        "Category",
        "Item Purchased",
        COUNT("Customer ID") AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT("Customer ID") DESC
        ) AS item_rank
    FROM shopping_behavior
    GROUP BY "Category","Item Purchased"
)
SELECT
    item_rank,
    "Category",
    "Item Purchased",
    total_orders
FROM item_counts
WHERE item_rank <= 3;
"""

pd.read_sql_query(query, conn)

   item_rank     Category  Item Purchased  total_orders
0          1  Accessories  Item Purchased          1240
1          1     Clothing  Item Purchased          1737
2          1     Footwear  Item Purchased           599
3          1    Outerwear  Item Purchased           324